### ISSUE TITLE
@aws-sdk/sqs-client: QueueDoesNotExist does not include Error object in typings

### ISSUE THREAD

**Issue by petetnt** [aws/aws-sdk#516]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

`QueueDoesNotExist` in `@aws-sdk/client-sqs@3.300.00` does not include Error-object in typings:

The actual error:

```json
 {
        "name": "QueueDoesNotExist",
        "$fault": "client",
        "$metadata": {
            "httpStatusCode": 400,
            "requestId": "xxxxxxxx-xxxx-xxxx-xxxx-dec65912ad92",
            "attempts": 1,
            "totalRetryDelay": 0
        },
        "Error": {
            "Type": "Sender",
            "Code": "AWS.SimpleQueueService.NonExistentQueue",
            "Message": "The specified queue does not exist for this wsdl version.",
            "Detail": "",
            "message": "The specified queue does not exist for this wsdl version."
        },
        "RequestId": "xxxxxxxx-xxxx-xxx-xxxx-dec65912ad92",
        "xmlns": "http://queue.amazonaws.com/doc/2012-11-05/",
        "message": "UnknownError"
```

The types only include a mismatching subset/superset of those keys:

![image](https://user-images.githubusercontent.com/7641760/228848431-d4af400c-b7ca-409a-bc32-39917ad77ea8.png)

The `Error` object contains the needed metadata for debugging: the regular `err.message` is `UnknownError`, which is definitely wrong. 

In general the error object is kinda weird with `requestId` existing in `RequestId` and `$metadata.$RequestId`.

Finally according to this AWS blog one would assume that the Class would be `QueueDoesNotExistException` instead of `QueueDoesNotExist`: https://aws.amazon.com/blogs/developer/service-error-handling-modular-aws-sdk-js/ 

I assume that the issue is present in other error objects too, but didn't have the time or need to check.

### SDK version number

@aws-sdk/client-sqs@3.300.00

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v18.13.0

### Reproduction Steps

```js
  const QueueUrlCommand = new GetQueueUrlCommand({
    QueueName: 'NONEXISTENTFOOBARURL'
  });

  const { QueueUrl } = await client.send(QueueUrlCommand);
```

### Observed Behavior

Error is thrown, but the typings don't have the `Error` object.

### Expected Behavior

Error is thrown and either `message` contains `Error.message` or the typing have `err.Error` object in them.

### Possible Solution

Either `message` contains `Error.message` or the typing have `err.Error` object in them.

### Additional Information/Context

-

**Comment by RanVaknin** [comment]
Hi @petetnt this should have been solved by a recent migration of SQS to a new protocol. 

Can you please check and let us know?

Thanks,
Ran~

**Comment by petetnt** [comment]
Sorry for only getting back to this now @RanVaknin, sadly I do not have a SQS instance to test against anymore, so I cannot cehck it out. At least the typing in `@aws-sdk/client-sqs@3.565.00` have not changed, so unless the error itself has been changed after the new protocol migration the issue still persist. Do you have an example of the error thrown from the example command?

```
const client = new SQS( {region: "us-east-1"} );

async function run(){
    try {
        const data = await client.send(new GetQueueUrlCommand({
            QueueName: "foo-queue"
        }))
        console.log(data)
    } catch (e) {
        if (e instanceof QueueDoesNotExist){
            // handle queue does not exist
        }
    }
}
run()
```
